services:
  cassandra_2x:
    image: cassandra:2.2.19
    container_name: native_protocol_v3
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassanderNativeProtocolV3
    volumes:
      - native_protocol_v3_data:/var/lib/cassandra

  cassandra_3x:
    image: cassandra:3.11.11
    container_name: native_protocol_v4
    ports:
      - "9142:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassanderNativeProtocolV4
    volumes:
      - native_protocol_v4_data:/var/lib/cassandra

  cassandra_4x:
    image: cassandra:4.0.5
    container_name: native_protocol_v5
    ports:
      - "9242:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassanderNativeProtocolV5
    volumes:
      - native_protocol_v5_data:/var/lib/cassandra

volumes:
  native_protocol_v3_data:
  native_protocol_v4_data:
  native_protocol_v5_data:
