edition                      = "2021"
max_width                    = 80
reorder_imports              = true
reorder_modules              = true
use_field_init_shorthand     = true
use_small_heuristics         = "Default"
use_try_shorthand            = true

# U N S T A B L E   F E A U T U R E S ##########################################
unstable_features            = true
binop_separator              = "Front"
brace_style                  = "SameLineWhere"
condense_wildcard_suffixes   = true
doc_comment_code_block_width = 80
enum_discrim_align_threshold = 40
format_code_in_doc_comments  = true
format_macro_matchers        = true
format_strings               = true
imports_layout               = "Vertical"
imports_granularity          = "Module"
reorder_impl_items           = true
group_imports                = "StdExternalCrate"
struct_field_align_threshold = 40
struct_lit_single_line       = false
wrap_comments                = true
