[formatting]
align_comments        = true
align_entries         = true
allowed_blank_lines   = 1
array_auto_collapse   = true
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 80
compact_entries       = false
compact_arrays        = false
compact_inline_tables = false
indent_entries        = true
inline_table_expand   = false
indent_string         = "  "
reorder_arrays        = false
reorder_keys          = false
trailing_newline      = true
